- hosts: webservers
  become: yes
  tasks:
   - name: install docker
     yum:
      name: docker
      state: latest

   - name: install git packages
     yum:
       name: git
       state: latest

   - name: install apache webserver
     yum:
       name: httpd
       state: latest